export const departmentData = [
  ["Web Development & Technical", "web-technical"],
  ["Design & Creative", "design-creative"],
  ["Video Editing, Motion & Production", "video-motion-production"],
  ["Content & Copywriting", "content-copywriting"],
  ["Marketing & Social Media", "marketing-social"],
  ["Presentation & Production Operations", "presentation-production-operations"],
] as const;

export const brandData = [
  {
    name: "Fixen Media",
    slug: "fixen-media",
    sector: "creative_agency",
    accentColor: "#EC1C24",
    website: "https://fixenmedia.com",
    description: "",
  },
  {
    name: "Builtale",
    slug: "builtale",
    sector: "real_estate",
    accentColor: "#565439",
    website: null,
    description: "",
  },
  {
    name: "Doshok",
    slug: "doshok",
    sector: "fashion",
    accentColor: "#2B95A0",
    website: "https://doshok.com",
    description: "",
  },
  {
    name: "Accoraze",
    slug: "accoraze",
    sector: "saas",
    accentColor: "#1B2F6E",
    website: null,
    description: "Run your business, smarter.",
  },
  {
    name: "Wiki Bangla",
    slug: "wiki-bangla",
    sector: "media",
    accentColor: "#0AA278",
    website: "https://wikibangla.org",
    description: "Connecting the world to Bangladesh",
  },
  {
    name: "Ghora Fera",
    slug: "ghora-fera",
    sector: "other",
    accentColor: "#FE5C36",
    website: "https://ghorafera.com",
    description: "",
  },
  {
    name: "Mactie",
    slug: "mactie",
    sector: "other",
    accentColor: "#1E1E1E",
    website: null,
    description: "Smart. Sleek. Synced.",
  },
  {
    name: "Avagata",
    slug: "avagata",
    sector: "other",
    accentColor: "#213F6E",
    website: null,
    description: "Affordable Elegance",
  },
] as const;

export const jobData = [
  ["Web Developer", "web-developer", 1],
  ["WordPress Developer & Analyst", "wordpress-developer-analyst", 1],
  ["UI/UX Designer", "ui-ux-designer", 1],
  ["Web & Backend Security Analyst", "web-backend-security-analyst", 1],
  ["Brand Identity & Logo Designer", "brand-identity-logo-designer", 2],
  ["Advertising & Social Media Creative Designer", "ad-social-creative-designer", 2],
  ["Visual Communication Designer", "visual-communication-designer", 2],
  ["Commercial & Documentary Video Editor", "commercial-documentary-video-editor", 3],
  ["Short-Form & Social Media Video Editor", "short-form-video-editor", 3],
  ["Motion Graphics & Animation Artist", "motion-graphics-animation-artist", 3],
  ["Cinematographer", "cinematographer", 3],
  ["Product & Commercial Photographer", "product-commercial-photographer", 3],
  ["Creative Director & Production Lead", "creative-director-production-lead", 3],
  ["Script & Creative Content Writer", "script-creative-content-writer", 4],
  ["SEO, Website & Brand Content Writer", "seo-brand-content-writer", 4],
  ["Social Media & Community Manager", "social-media-community-manager", 5],
  ["Performance Marketing Specialist", "performance-marketing-specialist", 5],
  ["On-Camera Presenter & Content Host", "on-camera-presenter-host", 6],
  ["Production Coordinator", "production-coordinator", 6],
] as const;
